apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: nebula-aurora-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula-aurora-assignment
  template:
    metadata:
      labels:
        app: nebula-aurora-assignment
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
