apiVersion: v2
name: nebula-aurora-assignment
description: A Helm chart for the User and Post API with Monitoring
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kube-prometheus-stack
    version: 51.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
